language: groovy
jdk:
  - oraclejdk8
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
sudo: required
branches:
  only:
    - master
services:
  - docker
go:
  - 1.9.x
before_script:
  - echo "Installing kubectl"
  - wget -O kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/darwin/amd64/kubectl
  - chmod +x kubectl
  - sudo mv kubectl /usr/local/bin/kubectl
  - kubectl
script:
  - ./gradlew build publishApiImage -PdockerRegistryUsername=$DOCKER_REGISTRY_USERNAME -PdockerRegistryPassword=$DOCKER_REGISTRY_PASSWORD

deploy:
  provider: script
  script: ci/deploy.sh
  on:
    branch: master
