language: groovy
jdk:
  - oraclejdk8
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

sudo: required
dist: trusty
services:
  - docker

install:
  - sudo apt-get --yes install snapd
  - sudo snap install kubectl --classic
  - sudo ln -s /snap/bin/kubectl /usr/local/bin/kubectl

branches:
  only:
    - master

script:
  - ./ci.sh docker

deploy:
  provider: script
  script: ./ci.sh update
  on:
    branch: master
