apiVersion: v1
kind: Namespace
metadata:
  name: rafflethor
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  namespace: rafflethor
spec:
  selector:
    matchLabels:
      app: rafflethor
      tier: api
  replicas: 1
  template:
    metadata:
      labels:
        app: rafflethor
        tier: api
    spec:
      containers:
      - image: rafflethor-docker-rafflethor.bintray.io/api:1.0.9
        name: api
        ports:
        - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: rafflethor
spec:
  ports:
  - port: 5050
    targetPort: 5050
    protocol: TCP
  selector:
    app: rafflethor
    tier: api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api
  namespace: rafflethor
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: api.services.rafflethor.io
    http:
      paths:
      - path: /
        backend:
          serviceName: api
          servicePort: 5050
